/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github_workflow_practice;

public class App {
    public String getGreeting() {
        return "Cito M";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
